### ISSUE TITLE
Добавление гайдов по старым версиям

### ISSUE THREAD

**Issue by stalker57241** [mc-modding/book#10]
Пока в учебнике я обнаружил только гайд по 1.12+. Я пока накидываю гайд для 1.9. Что насчёт более **ранних** версий?

**Comment by Ivasik78** [comment]
Учебник для 1.7.10 будет, но для версий ниже - нет, так как нет необходимости рассказывать о том, что уже для 1.2-1.6 уже и так навалом в интернете. По сути мы и 1.7.10 не должны поддерживать, но всё же интерес к данной версии не утихает и следовательно написать учебник стоит.
