### ISSUE TITLE
Лицензия?

### ISSUE THREAD

**Issue by andreymal** [mc-modding/book#12]
>...единого источника информации, который поддерживается сообществом

Сообщество, вероятно, будет не очень заинтересовано поддерживать нечто, что распространяется непонятно на каких условиях. Какой-нибудь [Creative Commons](https://creativecommons.org/licenses/by-sa/4.0/deed.ru) не помешал бы, как на той же Minecraft Wiki.

[![](https://licensebuttons.net/l/by-sa/4.0/88x31.png)](https://creativecommons.org/licenses/by-sa/4.0/deed.ru)

<sup>P.S. Также сообществу может не очень понравиться, что его вклад [периодически выкидывают](https://github.com/mc-modding/mc-modding-book), но это уже другая история.</sup>

<sup>P.P.S. У вас на сайте в меню нерабочая ссылка 1.12 → Предмет → Метадата</sup>

**Comment by Ivasik78** [comment]
1. На рассмотрении
2. Ничего не выкинуто, не хватает редакторов учебника
3. Уже исправили в f329d7e

**Comment by andreymal** [comment]
А лицензия так и не появилась...
