### ISSUE TITLE
Проблема с страницей "Прокси"

### ISSUE THREAD

**Issue by SuperTemich2005** [mc-modding/book#14]
Файлы с прокси у меня хранятся в директории com/st/openpsi/proxy/ClientProxy и com/st/openpsi/proxy/CommonProxy. В главном файле мода (находится в директории com/st/openpsi) прописываю следующие строки:
`import com.st.openpsi.proxy.CommonProxy`
`@SidedProxy(clientSide = "com.st.openpsi.proxy.ClientProxy", serverSide = "com.st.openpsi.proxy.CommonProxy")`
`public static CommonProxy proxy;`
Всё, как в гайде на странице [https://mcmodding.ru/1.12/basics/proxy/](url)
Сверил код-пример главного файла с тем, что у меня вышло в конце.
Запускаю таск build. Выбрасывает с ошибкой "W:\OpenPSI\build\sources\main\java\com\st\openpsi\OpenPsi.java:3: error: package com.st.openpsi.proxy does not exist
import com.st.openpsi.proxy.CommonProxy;"
![image](https://user-images.githubusercontent.com/39464061/77581311-304b5c00-6ee6-11ea-95ac-78e65f7810cf.png)

**Comment by Ivasik78** [comment]
![Screenshot](https://user-images.githubusercontent.com/9529993/83362610-520c0800-a39b-11ea-834f-04c985753e57.png)
У вас вместо классов ClientProxy и CommonProxy созданы папки ClientProxy и CommonProxy
