### ISSUE TITLE
mcpmod.info file - the question of its location

### ISSUE THREAD

**Issue by SEN5AI** [mc-modding/book#19]
### I certainly do not write a mod, but I do my own build. I would like to make it as high quality as possible, I pay attention to everything that is possible. The fact is that I have a mod that is installed only in minecraft.jar. However, the jar file already has mcpmod.info (from forge), but in order for the mod menu to be visible and that mod, you should throw it mcpmod.info. Then it turns out that I will replace mcpmod.info from forge and information about it will no longer be visible. I tried to put the archive separately with mcpmod.info to the mods folder, but it didn't work. Is it possible to add information about different mods in one mcpmod.info? Is there a way for everything to work?
_Thank you in advance_

**Comment by Icosider** [comment]
`[
{
    "modid": "inventorytweaks",
    "name": "Inventory Tweaks",
    "description": "Tweaks to inventory handling for ease of use, including sorting and automatic replacement of broken tools or exhausted stacks of items.",
    "mcversion": "1.7.10",
    "version": "1.59-dev-152-cf6e263",
    "url": "https://github.com/Kobata/inventory-tweaks",
    "updateUrl": "",
    "authors": [
        "Jimeo Wan",
        "Kobata"
    ],
    "credits": "By Jimeo Wan, updated for Forge by Kobata",
    "logoFile": "/invtweaks.png",
    "screenshots": [
    ],
    "parent":"",
    "dependencies": [
    ]
},
{
    "modid": "newMod",
    "name": "New Mods",
    "description": "New desc",
    "mcversion": "1.7.10",
    "version": "1.59-dev-152-cf6e263",
    "url": "https://github.com/Kobata/inventory-tweaks",
    "updateUrl": "",
    "authors": [
        "Jimeo Wan",
        "Kobata"
    ],
    "credits": "By Jimeo Wan, updated for Forge by Kobata",
    "logoFile": "logo.png",
    "screenshots": [
    ],
    "parent":"",
    "dependencies": [
    ]
},
]`
Look at that example

**Comment by SEN5AI** [comment]
> Посмотрите на этот пример
> [Ссылка](https://pastebin.com/ErvcvQX8)
Somehow it didn't work.
Perhaps I even made a mistake in such a simple task, look:
```
[
{
  "modid": "mod_SmeltableGravel",
  "name": "SmeltableGravel",
  "description": "Adds a recipe that turns gravel into silicon.",
  "version": "1.0",
  "mcversion": "1.5.1",
  "url": "https://sites.google.com/site/kinyoshimods/",
  "updateUrl": "",
  "authors": [
    "Kinyoshi"
  ],
  "credits": "",
  "logoFile": "",
  "screenshots": [
  ],
  "parent":"",
  "dependencies": [
  ]
},
{
  "modid": "KinyoshiMods_CraftGunpowder",
  "name": "CraftGunpowder",
  "description": "Craft gunpowder out of bonemeal, flint, sugar and coal or charcoal.",
  "version": "1.0",
  "mcversion": "1.5.1",
  "url": "https://sites.google.com/site/kinyoshimods/",
  "updateUrl": "",
  "authors": [
    "Kinyoshi"
  ],
  "credits": "",
  "logoFile": "",
  "screenshots": [
  ],
  "parent":"",
  "dependencies": [
  ]
},
]
```
If anything, 1 description works!

**Comment by Icosider** [comment]
Send me log file when game was started

**Comment by SEN5AI** [comment]
> Отправить мне файл журнала, когда игра была запущена

ForgeModLoader-client-0.log (This is the only log I cleaned):
[ForgeModLoader-client-0.log](https://github.com/mc-modding/book/files/5085176/ForgeModLoader-client-0.log)

**Comment by SEN5AI** [comment]
> Отправить мне файл журнала, когда игра была запущена

Dude, I don't think log will give you anything. The mod is loaded and running. You can either tell me if you understand this question, or not.
