### ISSUE TITLE
setUnlocalizedName -> setTranslationKey

### ISSUE THREAD

**Issue by neverlessy** [mc-modding/book#28]
ошибка тут https://github.com/mc-modding/book/blob/master/docs/1.12/block/basics/index.md
this.setUnlocalizedName(name);
в новых версиях заменено на 
this.setTranslationKey(name);

Из-за этой ошибки переодически проскакивают вопросы на форуме.
Ну или добавьте в скобочки, что может быть еще setTranslationKey

**Comment by Icosider** [comment]
А ничего что это другие маппинги? В текущей версии 1.12.2 Forge используются снапшот маппинги, а setTranslationKey присутствует в стейбл и устанавливать их нужно вручную
