### ISSUE TITLE
новые версии?

### ISSUE THREAD

**Issue by SupinePandora43** [mc-modding/book#4]
где гайды про FORGE 1.13/1.14 ?

**Comment by WantaSanchez** [comment]
Думаю будут намного позже так как до сих пор нету стабильных сборок Forge, а это значит, что много чего может быстро изменится.

**Comment by SupinePandora43** [comment]
а что насчёт `fabric`?!

**Comment by RareScrap** [comment]
@SupinePandora43 А кому нужен фабрик, когда можно просто подождать новый фордж?

**Comment by SupinePandora43** [comment]
@RareScrap forge очень долго обновляется (между версиями майнкрафта), когда фабрик быстрее

**Comment by RareScrap** [comment]
Конечно быстрее, ведь фабрик это прост инжектор кода в игру. В то время как фордж это целый фреймворк.

**Comment by WantaSanchez** [comment]
@SupinePandora43, сейчас долго обновляется ибо они много чего по новой делают. Раньше они достаточно быстро обновлялись.

**Comment by SupinePandora43** [comment]
@WantaSanchez из-за этого и начали появляться алтернативы

**Comment by WantaSanchez** [comment]
@SupinePandora43, да, но они, как сказал @RareScrap, лишь инжекторы кода. Тогда как Forge это полноценный API который не только подключает код мода к игре, но и упрощает процесс написания самого мода.

**Comment by SupinePandora43** [comment]
есть fabric-api

**Comment by RareScrap** [comment]
@SupinePandora43 Почему бы тогда тебе самому не внести вклад в учебник и не написать пару гайдов по фабрику?

**Comment by Ivasik78** [comment]
Fabric сырой, а также данный modLoader используют не все моды. Нет смысла писать под него учебник. В приоритете: Bukkit + Bungeecord, Sponge, Forge и не более!
