### ISSUE TITLE
1.7.10: Пара ошибок в статье про еду

### ISSUE THREAD

**Issue by MJaroslav** [mc-modding/book#42]
* В статье сказано, что поле `ItemFood#healAmount` отвечает за пополняемое количество здоровья игрока, но это не так. Дело в том, что в игре голод реализован в виде двух шкал: собственно, голод, который мы видим в GUI и насыщение (работает по тому же принципу, что и голод, но блокирует его убывание, пока не израсходуется), которое мы в GUI не видим. Это можно увидеть, просмотрев цепочку вызовов из `ItemFood`, либо поиграв с модом [AppleSkin](https://www.curseforge.com/minecraft/mc-mods/appleskin) (правда, я не помню его родителя на версии 1.7.10, но он точно есть).
* Выходя из первого пункта, поле `ItemFood#saturationModifier` отвечает за то самое невидимое игроку насыщение. Можно в статье объяснить это второй полоской голода, после исчерпания которой будет задействована основная. Ну или статью с вики прикрепить, лол.
* Описание `potionAmplifier` можно оставить без "некий уровень зелья", так как это он и есть: для эффекта сила 2 это значение будет 1, и так далее. Ну это чисто занудство.
* Можно еще уточнить, что эффект зелья можно задать только один, а то я, например, этого не узнал, если бы не полез в класс проверять работу `healAmount`.

**Comment by Icosider** [comment]
1. Тут я не доглядел, посмотрел на волка и дальше не стал. Поправлю.
2. "Чем больше значение, тем дольше игрок не будет тратить очки голода." это указано в статье.

Изменил 3 и 4 пункты, спасибо)

**Comment by Icosider** [comment]
@MJaroslav, посмотри ПР с инструментами. Сейчас думаю ещё создам ПР с едой
