### ISSUE TITLE
Тёмная тема

### ISSUE THREAD

**Issue by Icosider** [mc-modding/book#44]
@CMTV, учебнику не хватает тёмной темы, будет возможность реализовать возможность переключения темы?

**Comment by CMTV** [comment]
Да, завтра займусь этой фичей.

**Comment by CMTV** [comment]
Темная тема добавлена как часть "Большого обновления ядра".

https://github.com/mc-modding/book/commit/1d9879ce3717146f6ffa25d54ec3b19c6ffae57d
