### ISSUE TITLE
1.7.10: Предложение правок инструментов

### ISSUE THREAD

**Issue by MJaroslav** [mc-modding/book#45]
Не дождались, пока я проснусь и посмотрю.

Ну, короче, вот:

* В `Item.ToolMaterial` есть `setRepairItem(ItemStack)`, который назначает предмет для починки инструмента в наковальне. Думаю, о нем можно рассказать.
* Ты привёл пример какой урон добавляется от разных типов инструментов, но не привел пример про уровни добычи: обсидиан уровень 3, алмазная, изумрудная, золотая и редстоун руды 2, железная и лазуритовая 1, уголь, камень и все остальное 0.
* И еще раз про значения волшебных переменных: лучше ссылаться на википедию или добавить таблицу как распределены параметры у ванильных вещей в качестве примера. А то мне, как минимум, постоянно приходилось узнавать оптимальные значения методом тыка.
* В примере с топором (/да и с киркой тоже) можно было обойтись и наследованием от `ItemAxe` (/`ItemPickaxe`), так как по итогу ты просто повторил его код.
* Стоит уточнить список "классов" инструментов для `setHarvestLevel(String, int)`, так как может произойти путанница из-за маппинга лопаты как `ItemSpade`, а её "класса" как `shovel`. Список: `axe`, `pickaxe`, `shovel`. Ну либо можно наследоваться от нужного типа инструмента сразу.
* Раз я предложил насоедовать сразу нужный тип инструмента, то про методы `func_150893_a(ItemStack, Block)` и `func_150897_b(Block)` можно рассказать сразу в главе про мультитул.
* Сейчас заметил, что `setHarvestLevel(String, int)` все равно придется вызвать в инструменте, даже если он унаследован от нужного типа, так как уровень добычи будет 0, а не тот, что в материале.
* Думаю можно в начале статьи пояснить за `ItemTool` наследование с пометкой в стиле "О своих списках блоков и уроне читайте в главе мультитул".

Всякие примеры с параметрами из ваниллы о которых я не первый раз упоминаю уже, я, наверное, сам позже добавлю через PR.

// Я, кстати, не вижу особой проблемы, что в прод постоянно поочередно коммиты с правками улетают. Автодеплой для этого и сделан, думаю.

**Comment by Icosider** [comment]
1. О нём в отдельной статьей будет сказано, либо я объединю в одну
2 и 3 можно посмотреть в коде, смысл лишь в том, чтоб давать основу, далее разработчик самостоятельно должен изучать код иначе всё сведётся к CopyPast
4. До конца прочитай, я сделал пояснение
5. Да, забыл совсем что у них используется spade и shovel...
6. О них рассказано в каждой главе где используется(случаи повторения не в счёт)
7. Комментарии излишне
8. Опять же, мы делаем СВОЮ реализацию, а не "наследуемся от какого-то класса" и радуемся, что мы это сделали. А потом ведь у людей возникают вопросы, как добавить свой блок для добычи и прочее. Это не подходит только для мультитулла.

На счёт параметров из ванили, пояснения есть в статьях. Но мы обсуждали этот момент и все сошлись на варианте с JavaDoc.

По поводу пуша в мастер ветку, тут скажу так, сейчас я запушил инструменты в прод, а завтра ты пишешь ревью. Это неправильно. Надо чтобы ревьювился PR и затем только мёржился с продом, иначе так и будем к одной статье по 20 коммитов исправлений лепить.

**Comment by Icosider** [comment]
Доп. пояснение к 2 пункту: как вариант, я могу формировать таблицы, чтобы упростить жизнь, но это опять же идёт к тому, что мы чуть-ли не носом тыкаем разработчиков, которые на секундочку, уже знают Java и могут самостоятельно изучить классы.

**Comment by MJaroslav** [comment]
>2

Ну я сколько не читаю то как ты описываешь параметры и у меня складывается впечатление, что ты сам иногда не знаешь как они работают. Вот я и предлагаю примеры приводить, чтобы от них отталкиваться в своих значениях)

Про копипаст, ты сказал, что это сделано ради его предотвращения, но сам ты этот самый копипаст и сделал. Просто чаще всего добавляют обычные инструменты (условные бронзовые, стальные итд), вот им обычно менять ничего не нужно. А вот в мультитуле можно было бы сноску добавить, что конкретно сам по себе мультитул делать не обязательно, если нужны только свои блоки ломания, то вот такой-то вам метод.

~~В своем идеале учебника я бы ваще чуть бы не каждый метод расписанным вижу, особенно каждый, что без маппингов или явадока)~~

**Comment by Icosider** [comment]
В чём я действительно "плаваю", так это в генерации миров, там реально поверхностные знания. На счёт остального не сомневайся - знаю как работают, иногда могу допустить ошибку, но тут скорей играет фактор того, что я не пишу предметы, а разрабатываю совершенно другие вещи :) И да, откуда такое впечатление возникло? У меня было лишь пара статей по 1.12 и вот сейчас с нуля пишу 1.7.10, где от силы 2-3 статьи с конкретным кодом.

**Comment by Icosider** [comment]
Если же ты решил судить по статье с едой, то там я действительно не доглядел, а смысла расписывать формулу расчёта пополнения голода особо нет, так как ведёт от основной темы. Как я уже сказал, основная задача научить добавлять те или иные вещи в майн, а не учить разработчика включать голову и подносить всё на блюдечке. Если хочешь, можешь сделать JavaDoc ко всему майну, будет полезно для многих :D

**Comment by Icosider** [comment]
"Просто чаще всего добавляют обычные инструменты" а изменение списка добываемых блоков пойдёт лесом?) Как ты представляешь себе, создал разработчик медную кирку, а она у него не ломает камень из его мода. Как выкручиваться будет? Рефлексия или копипаст имеющегося кода в самом классе кирки? Я думаю выбор очевиден. Возможно конечно стоит разбирать методы, а именно свои условия выставлять, но тут уже они сами разберутся, им главное пояснить, что метод делает(в статьях я стараюсь расписывать логику работы того или иного метода)

**Comment by MJaroslav** [comment]
> На счёт остального не сомневайся

> Откуда пошло

Ну я и говорю, что только впечатление, в тебе-то я уверен. Просто иногда слишком просто о чем-то напишешь, а я начинаю просить уточнять. (Опять же, по мне важнее пояснить за майнинг лвл, чем за доп урон у предметов к материалу).

> можешь сделать JavaDoc ко всему майну

Ну, смотря на fucn'и в статьях учебника я как минимум захотел сделать свою версию маппингов, но чета разбираться с подключением и прочим как-то влом.

> а изменение списка добываемых блоков пойдёт лесом

Обычные инструменты должны работать как обычные (в наследниках на каждый тип инструмента в ванилле уже приделана проверка по материалу, который он может добывать: камень кирке, дерево топору и тд). Ничего тут не сломается.

> создал разработчик медную кирку, а она у него не ломает камень из его мода.

Ну во-первых, тогда и любой другой мод не сможет его камень ломать, если у него материал не rock. Я предлагаю вещи из идеи соместимости с forge и другими модами. Во-вторых про свои кастомные блоки я предложил сноску сделать в мультитуле в стиле "что достаточно такой-то метод переопределить".

> пояснять методы

Это да, в майне я бы сказал всё ой как насрано, что частая ситуация, когда не разобравшись в вызовах метода (особенно того, что без мапы и доков) твоя задумка либо работает наполовину, либо что-то ломает.

**Comment by Icosider** [comment]
У меня была идея подрубить офф маппинги на 1.7, но я пока не смотрел как начинает вести себя майн этой версии с маппингами 1.16)

> Обычные инструменты должны работать как обычные (в наследниках на каждый тип инструмента в ванилле уже приделана проверка по материалу, который он может добывать: камень кирке, дерево топору и тд). Ничего тут не сломается.
Я не говорю, что сломается, я о том, что в дальнейшем он наверняка захочет, чтобы его кирка могла ломать опр. блоки, а не только те, что добавляет сам майн. Тут даже скорей не создание своей кирки, а некий ликбез по работе с ItemTool(очень грубо говоря)

> Ну во-первых, тогда и любой другой мод не сможет его камень ломать, если у него материал не rock. Я предлагаю вещи из идеи соместимости с forge и другими модами. Во-вторых про свои кастомные блоки я предложил сноску сделать в мультитуле в стиле "что достаточно такой-то метод переопределить".
Ты очень сильно придираешься, с таким подходом, можно всегда только от ванильных предметов наследоваться и получить некий McCreator, только без гуишки

> Это да, в майне я бы сказал всё ой как насрано, что частая ситуация, когда не разобравшись в вызовах метода (особенно того, что без мапы и доков) твоя задумка либо работает наполовину, либо что-то ломает.
Тут уж да, проблема. Я когда писал статью с инструментами, по началу хотел наследоваться от ItemAxe и прочих, но опять же, меня отталкивает тот факт, что уменьшается возможность контролирования всего процесса в моём же собственном инструменте(выше писал)

**Comment by MJaroslav** [comment]
> с таким подходом, можно всегда только от ванильных предметов

Ну конкретно в твоем примере реально так можно сделать. 

> mcreator 

Всё, что нельзя реализовать наследованием и правкой параметров уже реализуется как раз путем наследования родителя и/или встраиванием вызовов фордж событий.

---

Я клоню к тому, что можно хоть сноску такого типа уже добавить: "если вам нужен просто инструмент но из своего матриала, можете смело наследоваться от нужного типа инструмента".

---

> всё в цитатах

Тут рендер тоже ломается, если нет пустых строк, хех.

**Comment by Icosider** [comment]
> Я клоню к тому, что можно хоть сноску такого типа уже добавить: "если вам нужен просто инструмент но из своего матриала, можете смело наследоваться от нужного типа инструмента".
Да, с этим согласен :)

> Тут рендер тоже ломается, если нет пустых строк, хех.
Вообще это странно, что наш движок ломает рендер списков, если там нет пропуска строки, так как сам markdown не ломается, проверял как минимум в 2 текстовых редакторах

**Comment by Icosider** [comment]
![image](https://user-images.githubusercontent.com/9529993/167586497-fb570edc-859f-4b40-8285-07b868cfe68d.png)

**Comment by Icosider** [comment]
Если что-то останется, то переоткроем Issue.

**Comment by MJaroslav** [comment]
Мегахарош, но дословно мой текст не копируй, а то получается "Обсидиан уровень 3, ...".

**Comment by Icosider** [comment]
> Мегахарош

Так да, прислушиваюсь к предложениям по улучшению 😁
