### ISSUE TITLE
Контрибьюторы статей

### ISSUE THREAD

**Issue by Icosider** [mc-modding/book#46]
Раньше на сайте, в подвале, отображались конки тех, кто вносил вклад. Сейчас такого почему-то нет. Предлагаю это вернуть, но с небольшим переосмыслением. Вместо того, чтобы отображать иконки, оформить как некую карточку с подписью "Внесли вклад".

**Comment by MJaroslav** [comment]
Я думал, кстати, что плашка просто сломалась.

**Comment by CMTV** [comment]
Эта плашку я самостоятельно допилил к существующей теме. Он она уже какое-то время поломанной была, как и навигация по статьям. На выходных попробую запилить.

**Comment by Icosider** [comment]
Кстати, было бы неплохо иметь возможность скрывать навигацию по статьям

**Comment by Icosider** [comment]
И соглашусь с @TheAndrey, favicon лучше вернуть прежний, ибо непонятный квадрат серого цвета

**Comment by CMTV** [comment]
@Icosider что значит скрывать навигацию?

А по поводу favicon даже не знаю. Идея была такая, что у форума блок травы, а учебник это уже глубже, то есть камень...
Если добавить квадратные скобки, то иконка будет очень мелкой и к тому же будет отличаться от иконки форума...

**Comment by TheAndrey** [comment]
Раньше была хорошая иконка, никто не жаловался. И цвет шапки поменять. Нынешний зелёный цвет заменить на более тёплый оттенок.

**Comment by CMTV** [comment]
Нет, раньше была отстойная иконка, мелкая, скобок не видно, в темном браузере вообще они пропадают.
Плюс она отличалась от иконки форума.

А в чем проблема холодного зеленого цвета? Мне вполне нравится.
Проблема в том, что любой цвет не поставить. Можно только что-то из [вот этого](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/).

**Comment by TheAndrey** [comment]
Своими стилями добить, аналогично скрытию подвала страницы (зачем?).

**Comment by CMTV** [comment]
Это только звучит просто. На деле нужно отловить все места появления цвета на сайте.
Потом это еще и отломаться может с обновлениями.

**Comment by Icosider** [comment]
> @Icosider что значит скрывать навигацию?
> 
> А по поводу favicon даже не знаю. Идея была такая, что у форума блок травы, а учебник это уже глубже, то есть камень... Если добавить квадратные скобки, то иконка будет очень мелкой и к тому же будет отличаться от иконки форума...

Слева показывается навигация по статьям, сделать возможность скрывать эту панель, а то на мелких экранах читать статьи проблемно

**Comment by CMTV** [comment]
@Icosider на мелких экранах она автоматом скрывается.

**Comment by CMTV** [comment]
Исправил и "Вклад внесли" и цвета.

https://github.com/mc-modding/book/commit/5548ea8e3f40ade0ff92ea4064d36cae6c6e13b2

**Comment by Icosider** [comment]
> @Icosider на мелких экранах она автоматом скрывается.

Не на всех

**Comment by TheAndrey** [comment]
Не увидел такой проблемы. На этом разрешении шрифты становятся меньше, все прекрасно помещается на странице.

**Comment by CMTV** [comment]
Синий цвет исправил.
