### ISSUE TITLE
Ссылки на скачивание JDK

### ISSUE THREAD

**Issue by RareScrap** [mc-modding/book#8]
Т.к. Oracle требует регистрацию чтобы выкачивать JDK - предлагаю хранить бинарники локально прямо на mcmodding.ru. Необходимость регистрации перед скачкой может смутить читающего и даже вынудить качать с неизвестных источников.

**Comment by Ivasik78** [comment]
В регистрации через офф. сайт oracle нет ничего такого, но идея взята на рассмотрение!

**Comment by SupinePandora43** [comment]
предлагаю [AdoptOpenJDK](https://adoptopenjdk.net)

**Comment by Ivasik78** [comment]
@SupinePandora43, есть куда лучше, чем этот AdoptOpenJDK
